apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1 # {"$ref":"#/definitions/io.k8s.cli.setters.replicas"}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: go-web-server
        image: jasonblanchard/go-web-server
